const SECONDS_PER_HOUR = 3600;
const SECONDS_PER_MINUTE = 60;

const HAFT_DAY_SECONDS = 12 * SECONDS_PER_HOUR - 1; // 11h59m59s

const DEFAULT_DURATION = 15 * SECONDS_PER_MINUTE;

const DEFAULT_TIME_FORMAT = 24;

const DEFAULT_GROUP_TIME = 60 * SECONDS_PER_HOUR;

const DEFAULT_WORKING_TIME = {
  start: 8 * SECONDS_PER_HOUR,
  end: 24 * SECONDS_PER_HOUR,
};

const DEFAULT_DATE_FOTMAT = "YYYY-MM-DD";

const DEFAULT_TIME_FOTMAT = "hh:mm:ss";

const DEFAULT_DATE_TIME_FOTMAT = "DD MM YYYY hh:mm:ss";

export const CONFIG = {
  SECONDS_PER_HOUR,
  SECONDS_PER_MINUTE,
  HAFT_DAY_SECONDS,
  DEFAULT_DURATION,
  DEFAULT_TIME_FORMAT,
  DEFAULT_GROUP_TIME,
  DEFAULT_DATE_FOTMAT,
  DEFAULT_TIME_FOTMAT,
  DEFAULT_DATE_TIME_FOTMAT,
  DEFAULT_WORKING_TIME,
};
